import { Product } from './types';

export const initialProducts: Product[] = [
  {
    id: 1,
    ten: 'iPhone 15 Pro',
    danhMuc: 'Điện tử',
    gia: 25000000,
    soLuong: 10,
    moTa: 'Điện thoại thông minh cao cấp với chip A17 Pro, camera 48MP, và màn hình Super Retina XDR',
  },
  {
    id: 2,
    ten: 'Áo Thun Nam',
    danhMuc: 'Quần áo',
    gia: 150000,
    soLuong: 50,
    moTa: 'Áo thun cotton 100% thoáng mát, co giãn, phù hợp với mọi mùa',
  },
  {
    id: 3,
    ten: 'Cơm Chiên Dương Châu',
    danhMuc: 'Đồ ăn',
    gia: 45000,
    soLuong: 100,
    moTa: 'Cơm chiên Dương Châu ngon cơm chiên trứng, tôm, thịt, hành',
  },
  {
    id: 4,
    ten: 'Clean Code',
    danhMuc: 'Sách',
    gia: 320000,
    soLuong: 20,
    moTa: 'Cuốn sách hướng dẫn viết code sạch và dễ bảo trì, tác giả Robert C. Martin',
  },
  {
    id: 5,
    ten: 'Samsung Galaxy Watch',
    danhMuc: 'Điện tử',
    gia: 8500000,
    soLuong: 15,
    moTa: 'Đồng hồ thông minh Samsung với công nghệ theo dõi sức khỏe tiên tiến',
  },
  {
    id: 6,
    ten: 'Quần Jeans Nam',
    danhMuc: 'Quần áo',
    gia: 350000,
    soLuong: 40,
    moTa: 'Quần jeans nam thời trang, co giãn, bền màu, nhiều size',
  },
  {
    id: 7,
    ten: 'Phở Bò',
    danhMuc: 'Đồ ăn',
    gia: 55000,
    soLuong: 80,
    moTa: 'Phở bò đặc trưng Việt Nam, nước dùng ngon, thịt mềm',
  },
  {
    id: 8,
    ten: 'Lập Trình React',
    danhMuc: 'Sách',
    gia: 280000,
    soLuong: 25,
    moTa: 'Sách hướng dẫn học React từ cơ bản đến nâng cao, có ví dụ thực tế',
  },
  {
    id: 9,
    ten: 'Laptop Dell XPS 13',
    danhMuc: 'Điện tử',
    gia: 35000000,
    soLuong: 8,
    moTa: 'Laptop siêu nhẹ, màn hình 4K, chip Intel Core i7, SSD 512GB',
  },
  {
    id: 10,
    ten: 'Váy Nữ Công Sở',
    danhMuc: 'Quần áo',
    gia: 450000,
    soLuong: 30,
    moTa: 'Váy nữ công sở thanh lịch, phù hợp đi làm, chất vải cao cấp',
  },
  {
    id: 11,
    ten: 'Pizza Hải Sản',
    danhMuc: 'Đồ ăn',
    gia: 120000,
    soLuong: 60,
    moTa: 'Pizza với phô mai mozzarella, tôm, mực, cơm chín vàng',
  },
  {
    id: 12,
    ten: 'Lập Trình Web với JavaScript',
    danhMuc: 'Sách',
    gia: 250000,
    soLuong: 35,
    moTa: 'Sách hướng dẫn lập trình web toàn diện, HTML, CSS, JavaScript, Node.js',
  },
];
